name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test
      run: |
       git config user.name "$(git log -n 1 --pretty=format:%an)"
       git config user.email "$(git log -n 1 --pretty=format:%ae)"
       gradle deployReports
