name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Define email
      run: git config user.email "jl_devel@outlook.com"
    - name: Define name
      run: git config user.name "Jacob Leith"
    - name: Build and test
      run: gradle deployReports
